const requests = {
  fetchKolkataWeather: "Kolkata",
  fetchDelhiWeather: "New Delhi",
  fetchLondonWeather: "London",
  fetchLAWeather: "Los Angeles",
  fetchMumbaiWeather: "Mumbai",
  fetchGuwuhatiWeather: "Assam",
  fetchTorontoWeather: "Toronto",
  fetchBangaloreWeather: "Bangalore",
  fetchFaroeWeather: "Faroe",
  fetchNewYorkWeather: "New York",
  fetchMadeiraWeather: "Madeira",
  fetchTokyoWeather: "Tokyo",
  fetchBeijingWeather: "Beijing",
  fetchMunichWeather: "Munich",
  fetchMoscowWeather: "Moscow",
  fetchGlasgowWeather: "Glasgow",
  fetchMadridWeather: "Madrid",
  fetchBerlinWeather: "Berlin",
  fetchRioWeather: "Rio",
  fetchTijuanaWather: "Tijuana",
  fetchSydneyWeather: "Sydney",
  fetchMelbourneWeather: "Melbourne",
  fetchAucklandWeather: "Auckland",
  fetchBangkokWeather: "Bangkok",
  fetchSingaporeWeather: "Singapore",
  fetchCairoWeather: "Cairo",
  fetchParisWeather: "Paris",
  fetchZurichWeather: "Zurich",
  fetchCapeTownWeather: "Cape Town",
  fetchMexicoWeather: "Mexico",
  fetchNairobiWeather: "Nairobi",
  fetchShanghaiWeather: "Shanghai",
  fetchChicagoWeather: "Chicago",
  fetchRomeWeather: "Rome",
  fetchLagosWeather: "Lagos",
};

export default requests;
